# 앙상블 분류 모델링

### RandomForest

In [204]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [205]:
wine=pd.read_csv("https://bit.ly/wine_csv_data")
data=wine[["alcohol","sugar","pH"]].to_numpy()
target=wine["class"].to_numpy()

In [206]:
from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target=train_test_split(data,target,test_size=0.2,random_state=42)

In [207]:
### 모델링

In [208]:
from sklearn.model_selection import cross_validate

from sklearn.ensemble import RandomForestClassifier

In [209]:
rf=RandomForestClassifier(n_jobs=-1, random_state=42,n_estimators=100) ## n_estimators => tree가 100개 만들어짐을 나타냄.

In [210]:
score=cross_validate(rf,train_input,train_target,return_train_score=True,n_jobs=-1)

In [211]:
score["train_score"]

array([0.9971133 , 0.99663219, 0.9978355 , 0.9973545 , 0.9978355 ])

In [212]:
score["test_score"]

array([0.88461538, 0.88942308, 0.90279115, 0.88931665, 0.88642926])

In [213]:
np.mean(score["train_score"])

np.float64(0.9973541965122431)

In [214]:
np.mean(score["test_score"])

np.float64(0.8905151032797809)

In [215]:
## 파라미터 최적화

In [216]:
from scipy.stats import uniform, randint
params={'min_impurity_decrease':uniform(0.0001,0.001),
        'max_depth': randint(20,50),
        'min_samples_split':randint(2,25),
        'min_samples_leaf':randint(1,25),
}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(rf,params,n_iter=100, n_jobs=1,random_state=42)

In [218]:
rs.fit(train_input,train_target)

RandomizedSearchCV(estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=100, n_jobs=1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E15930680>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x0000020E15C257C0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E1592F4A0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E1262D6A0>},
                   random_state=42)

In [219]:
best_rf=rs.best_estimator_

In [220]:
best_rf.score(train_input,train_target)

0.9043679045603232

In [221]:
best_rf.score(test_input,test_target)

0.8676923076923077

In [222]:
best_rf.feature_importances_

array([0.16271933, 0.61334545, 0.22393522])

In [223]:
params={'min_impurity_decrease':uniform(0.0001,0.001),
        'max_depth': randint(20,50),
        'min_samples_split':randint(2,25),
        'min_samples_leaf':randint(1,25),
        "n_estimators": randint(50,200)
}

In [224]:
rs= rs=RandomizedSearchCV(rf,params,n_iter=100, n_jobs=1,random_state=42)

In [225]:
rs.fit(train_input,train_target)

RandomizedSearchCV(estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=100, n_jobs=1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E15F9B830>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x0000020E15FD3E30>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E15F996A0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E15F98B90>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E157EEE10>},
                   random_state=42)

In [226]:
best_rf=rs.best_estimator_

In [227]:
best_rf.score(train_input,train_target)

0.9107177217625553

In [228]:
best_rf.score(test_input,test_target)

0.8723076923076923

In [229]:
# 그레디언트 부스팅

In [230]:
from sklearn.ensemble import GradientBoostingClassifier

gbt= GradientBoostingClassifier(n_estimators=100, max_depth=3, learning_rate=0.1, random_state=42)



In [231]:
scores=cross_validate(gbt,train_input,train_target,return_train_score=True, n_jobs=-1)


In [232]:
print(np.mean(scores["train_score"]))

0.8881086892152563


In [233]:
print(np.mean(scores["test_score"]))

0.8720430147331015


In [234]:
gbt.fit(train_input, train_target)

GradientBoostingClassifier(random_state=42)

In [235]:
gbt.score(train_input,train_target)

0.8880123147969983

In [236]:
gbt.score(test_input,test_target)

0.8669230769230769

In [237]:
params={'min_impurity_decrease':uniform(0.0001,0.001),
        'max_depth': randint(20,50),
        'min_samples_split':randint(2,25),
        'min_samples_leaf':randint(1,25),
        "n_estimators": randint(50,200),
        "learning_rate": uniform(0.0001,0.1)}

In [238]:
rs= rs=RandomizedSearchCV(gbt,params,n_iter=100, n_jobs=1,random_state=42)

In [239]:
rs.fit(train_input,train_target)

RandomizedSearchCV(estimator=GradientBoostingClassifier(random_state=42),
                   n_iter=100, n_jobs=1,
                   param_distributions={'learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x0000020E174FD7C0>,
                                        'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E15C26E70>,
                                        'min_impurity_decrease': <scipy.stats._distn_...s_frozen object at 0x0000020E1592F7A0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E174D38C0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E161B5190>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000020E174FF470>},
                   random_state=42)

In [240]:
rs.best_estimator_

GradientBoostingClassifier(learning_rate=np.float64(0.07034840839871093),
                           max_depth=35,
                           min_impurity_decrease=np.float64(0.0006528199769079078),
                           min_samples_leaf=10, min_samples_split=24,
                           n_estimators=75, random_state=42)

In [241]:
!pip install xgboost

In [242]:
from xgboost import XGBClassifier

In [243]:
xgb= XGBClassifier()

In [244]:
xgb.fit(train_input,train_target)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [245]:
xgb.score(train_input,train_target)

0.9468924379449682

In [246]:
xgb.score(test_input,test_target)

0.8746153846153846

In [ ]:
import pandas as pd 
import numpy as np

wine= pd.read_csv("https://bit.ly/wine_csv_data")

data=wine[["alcohol",'sugar','pH']].to_numpy()
target=wine['class'].to_numpy()

from sklearn.model_selection import train_test_split

train_input, test_input, train_target,test_target=train_test_split(data, target, train_size=0.2, random_state=42)

from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_jobs=-1,random_state=42)

scores=cross_validate(rf,train_input,train_target,return train_input,train)

